### ISSUE TITLE
Invalid model name results in segmentation violation

### ISSUE THREAD

**Issue by rhorber** [zhenghaoz/gorse#29]
When running `gorse serve -c config/gorse.toml` the command crashes:
```
2020/02/05 10:58:07 training model
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x917733]

goroutine 5 [running]:
github.com/zhenghaoz/gorse/engine.UpdateRecommends(0xc000104050, 0xc, 0xc004565110, 0x32, 0x1, 0xb7cdc0, 0xc0000de000, 0xc0000105a0, 0x0, 0x2)
        /root/gorse/engine/offline.go:89 +0x193
github.com/zhenghaoz/gorse/engine.Update(0xc00002bfc0, 0x7, 0x1f90, 0xc000104010, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/gorse/engine/offline.go:135 +0x1d8
github.com/zhenghaoz/gorse/cmd.watch(0xc00002bfc0, 0x7, 0x1f90, 0xc000104010, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/gorse/cmd/serve.go:85 +0x36b
created by github.com/zhenghaoz/gorse/cmd.glob..func7
        /root/gorse/cmd/serve.go:31 +0x30c
```

After some investigation I found out that I used an invalid model (`knn-implicit` instead of `knn_implicit`).

IMHO an invalid model should be reported instead of causing a segmentation fault.

**Comment by zhenghaoz** [comment]
Thank you so much :smile:
